// <auto-generated />
using MVC4Fun.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC4Fun.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20250712131519_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC4Fun.Models.Movie", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieID"));

                    b.Property<string>("Director")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Film")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("MovieID");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Director = "Dean Fleischer Camp",
                            Film = "Lilo & Stitch",
                            Year = 2025
                        },
                        new
                        {
                            MovieID = 2,
                            Director = "Wes Ball",
                            Film = "Kingdom of the Planet of the Apes",
                            Year = 2024
                        },
                        new
                        {
                            MovieID = 3,
                            Director = "Mike Mitchell",
                            Film = "Kung Fu Panda 4",
                            Year = 2024
                        },
                        new
                        {
                            MovieID = 4,
                            Director = "Christopher Edward Nolan",
                            Film = "Oppenheimer",
                            Year = 2023
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
